export const SET_CURRENT_DATE_CHANGE = '[CALENDAR] SET_CURRENT_DATE_CHANGE';
export const SET_CURRENT_DATE_KEY_CHANGE = '[CALENDAR] SET_CURRENT_DATE_KEY_CHANGE';
export const SET_DATE_SELECTED_CHANGE = '[CALENDAR] SET_DATE_SELECTED_CHANGE';
