export const SET_EVENT_FORM_CHANGE = '[EVENT] SET_EVENT_FORM_CHANGE';
export const SET_EVENT_FIELD_ERROR = '[EVENT] SET_EVENT_FIELD_ERROR';
export const FETCHING_EVENT_REQUEST = '[EVENT] FETCHING_EVENT_REQUEST';
export const FETCHING_EVENT_SUCCESS = '[EVENT] FETCHING_EVENT_SUCCESS';
export const FETCHING_EVENT_FAILURE = '[EVENT] FETCHING_EVENT_FAILURE';
export const SET_EVENT_ACTIVE_MODAL = '[EVENT] SET_EVENT_ACTIVE_MODAL';
